In [16]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 4  5  3  8 18]
[ 1 11 11 19  2]


In [7]:
li = [i+1 for i in li]
print(li)

[2, 3, 4, 5, 6]


In [8]:
# a = a+1
# a

array([17,  7,  2, 18, 15])

In [17]:
c = a + b
c

array([ 5, 16, 14, 27, 20])

In [11]:
d = a-b
d


array([-17,   8,  -8, -10,   7])

In [12]:
e = a*b
e

array([ 38,   9,   9, 171, 228])

In [13]:
f = a/b
f

array([0.10526316, 9.        , 0.11111111, 0.47368421, 1.58333333])

In [14]:
g = a//b

In [15]:
h = a%b
h

array([2, 0, 1, 9, 7], dtype=int32)

In [19]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

38
7.6
3
2
18
4


In [20]:
print(a>b)

[ True False False False  True]


In [21]:
print(a>b)

[ True False False False  True]


In [22]:
print(a==b)

[False False False False False]


In [23]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [25]:
a[2]=0
print(np.logical_not(a))

[False False  True False False]
