In [7]:
import numpy as np

x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)

[[6 6]
 [3 1]
 [8 6]]
[[7 6 7]
 [2 7 1]]


In [9]:
y = np.transpose(y)
ans = x-y
print(ans)

[[-1  4]
 [-3 -6]
 [ 1  5]]
