In [3]:
import numpy as np

a = [1,2,3]
b = np.array(a, dtype = int)
print(b)
print(type(b))


[1 2 3]
<class 'numpy.ndarray'>


In [9]:
b = np.ones((3,4),dtype=dict)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=object)

In [10]:
b = np.zeros(3, dtype=int)
b

array([0, 0, 0])

In [13]:
b = np.full(3,1)
b

array([1, 1, 1])