In [3]:
import numpy as np
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.arange(1,20,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
b = np.linspace(2,10)
b
print(b[1]-b[0])

0.16326530612244916


In [12]:
b = np.linspace(2,10,5, dtype=int, endpoint=False)
b

array([2, 3, 5, 6, 8])

In [14]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
b = np.random.rand(2,3)
b

array([[0.58505137, 0.19187754, 0.54572166],
       [0.82661294, 0.24164354, 0.90496802]])

In [18]:
b = np.random.rand(2,3)
b

array([[0.51305468, 0.76425232, 0.98309276],
       [0.291567  , 0.78741848, 0.45975119]])

In [20]:
b = np.random.rand(10)*10
b

array([2.37874953, 4.47294624, 8.63038589, 8.10439579, 6.24333885,
       0.90721772, 7.38722106, 8.9580205 , 9.19142861, 7.74487802])