In [4]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[1., -1., 2.],
              [2., 0., 0.1],
              [0., 1., -1.1]])

In [8]:
X_scaled = preprocessing.scale(X)

In [9]:
X_scaled.mean(axis = 0)

array([0.00000000e+00, 0.00000000e+00, 7.40148683e-17])

In [10]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [13]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.30587924],
       [ 1.22474487,  0.        , -0.18282309],
       [-1.22474487,  1.22474487, -1.12305615]])

In [14]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 1.00000000e+00,  1.00000000e+00, -7.40148683e-17]])